steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-west2-docker.pkg.dev/microservices-425700/image-registry/products-ms",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west2-docker.pkg.dev/microservices-425700/image-registry/products-ms",
      ]